// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0EOi--OPzvnLPbDGRuF7Lylrw4nKNwhc',
    appId: '1:553931152302:web:ad55fb9ba3600962b4463f',
    messagingSenderId: '553931152302',
    projectId: 'hm-motors',
    authDomain: 'hm-motors.firebaseapp.com',
    storageBucket: 'hm-motors.appspot.com',
    measurementId: 'G-7MWQ4JT98X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRnqkRmhMWQ60r0rzF61KY2a3Nt6sBVRc',
    appId: '1:553931152302:android:12bca3cf4e75c820b4463f',
    messagingSenderId: '553931152302',
    projectId: 'hm-motors',
    storageBucket: 'hm-motors.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG4GMyvV5b_oxHJYduuHD8CkrKCh_w2RI',
    appId: '1:553931152302:ios:72807deee14d6d04b4463f',
    messagingSenderId: '553931152302',
    projectId: 'hm-motors',
    storageBucket: 'hm-motors.appspot.com',
    iosClientId:
        '553931152302-jc6vt79mn3qe2t4eise59def41kqogmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmMotors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG4GMyvV5b_oxHJYduuHD8CkrKCh_w2RI',
    appId: '1:553931152302:ios:72807deee14d6d04b4463f',
    messagingSenderId: '553931152302',
    projectId: 'hm-motors',
    storageBucket: 'hm-motors.appspot.com',
    iosClientId:
        '553931152302-jc6vt79mn3qe2t4eise59def41kqogmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hmMotors',
  );
}
